// This file is autogenerated and manually modified: please see the codegen template "Options"
#ifndef PDFTRON_H_CPPPDFOfficeToPDFOptions
#define PDFTRON_H_CPPPDFOfficeToPDFOptions

#include <PDF/ConversionOptions.h>

namespace pdftron{ namespace PDF{ 

class OfficeToPDFOptions: public ConversionOptions
{
public:
	OfficeToPDFOptions();

	~OfficeToPDFOptions();



	
	/**
	* Gets the value LayoutResourcesPluginPath from the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @ return a UString, The path at which the pdftron-provided font resource plugin resides.
	*/
	UString GetLayoutResourcesPluginPath();

	/**
	* Sets the value for LayoutResourcesPluginPath in the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @param value: The path at which the pdftron-provided font resource plugin resides
	* @return this object, for call chaining
	*/
	OfficeToPDFOptions& SetLayoutResourcesPluginPath(const UString& value);

	
	/**
	* Gets the value ResourceDocPath from the options object
	* The path at which the a .docx resource document resides
	* @ return a UString, The path at which the a .docx resource document resides.
	*/
	UString GetResourceDocPath();

	/**
	* Sets the value for ResourceDocPath in the options object
	* The path at which the a .docx resource document resides
	* @param value: The path at which the a .docx resource document resides
	* @return this object, for call chaining
	*/
	OfficeToPDFOptions& SetResourceDocPath(const UString& value);

	
	/**
	* Gets the value SmartSubstitutionPluginPath from the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @ return a UString, The path at which the pdftron-provided font resource plugin resides.
	*/
	UString GetSmartSubstitutionPluginPath();

	/**
	* Sets the value for SmartSubstitutionPluginPath in the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @param value: The path at which the pdftron-provided font resource plugin resides
	* @return this object, for call chaining
	*/
	OfficeToPDFOptions& SetSmartSubstitutionPluginPath(const UString& value);
	
	double GetExcelDefaultCellBorderWidth();
	OfficeToPDFOptions& SetExcelDefaultCellBorderWidth(double width);

	OfficeToPDFOptions& SetAutoFillDict(const UString& dict);

	/**
	 * Gets the value ApplyPageBreaksToSheet flag from the options object
	 * Encodes whether Excel worksheets pagination is enabled
	 *
	 * @return a boolean, whether Excel worksheets pagination is enabled.
	 */
	bool GetApplyPageBreaksToSheet();
	/**
	 * Sets the value for ApplyPageBreaksToSheet in the options object
	 * Flag that switches on pagination of Excel worksheets
	 *
	 * @return this object, for call chaining
	 */
	OfficeToPDFOptions& SetApplyPageBreaksToSheet();

};

}
}

#include "../Impl/OfficeToPDFOptions.inl"
#endif // PDFTRON_H_CPPPDFOfficeToPDFOptions
